### ISSUE TITLE
Running in a docker container / remote server - throws exception (display bad name)

### ISSUE THREAD

**Issue by svscorp** [Evidlo/passhole#13]
Tried to run in a docker container:

```
root@75ccdf888d98:/host# ph --no-keyfile --database ./new-keepass.kdbx init
raceback (most recent call last):
  File "/usr/local/bin/ph", line 7, in <module>
    from passhole.passhole import main
  File "/usr/local/lib/python2.7/dist-packages/passhole/passhole.py", line 11, in <module>
    from pynput.keyboard import Controller, Key
  File "/usr/local/lib/python2.7/dist-packages/pynput/__init__.py", line 23, in <module>
    from . import keyboard
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

**Comment by Evidlo** [comment]
Try with version 1.7.5.

**Comment by svscorp** [comment]
Hi @Evidlo,

I will. Thanks.

**Comment by svscorp** [comment]
@Evidlo sorry, one more question. Do you think it is possible to make it working in non-interactive mode somehow?

If I try to run it in docker container withot `tty` it gives another message:
```
No usable Term::ReadLine::* modules found.
This list was tried:
 * Term::ReadLine::Gnu
 * Term::ReadLine::Perl
 * Term::ReadLine::Perl5
```

But meanwhile let me test new version to check whether previous error is gone.

**Comment by svscorp** [comment]
I have tried `passhole-1.7.6` and `python2` still issue:

```
root@2c3977add414:/host# ph --version
Traceback (most recent call last):
  File "/usr/local/bin/ph", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/passhole/passhole.py", line 782, in main
    parser = create_parser()
  File "/usr/local/lib/python2.7/dist-packages/passhole/passhole.py", line 727, in create_parser
    remove_parser = subparsers.add_parser('remove', aliases=['rm'], help="remove an entry")
  File "/usr/lib/python2.7/argparse.py", line 1066, in add_parser
    parser = self._parser_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases'
```

**Comment by svscorp** [comment]
Tried to install python3 and python3-pip, then: `pip3 install passhole`:

```
root@66c7d4a88918:/host# pip3 install passhole

Collecting passhole
  Downloading https://files.pythonhosted.org/packages/30/87/d5d557540f2c138b6bf9e305488a828166ec9a36ac8d086d755743b94c69/passhole-1.7.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mzilbm9c/passhole/setup.py", line 12, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1676: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mzilbm9c/passhole/
```

**Comment by svscorp** [comment]
(ubuntu bionic)

**Comment by svscorp** [comment]
my next challenge will be no-tty usage. I saw in your code you have some condition for non-tty situation, but wasn't able to get to that moment yet.

**Comment by Evidlo** [comment]
Yeah, python2 argparse doesn't support command aliases, so I guess I should list Passhole as python3 only now.  Can you provide a stripped down version of your dockerfile that exhibits the problem?

**Comment by Evidlo** [comment]
Also see here: https://github.com/docker-library/python/issues/13

**Comment by Evidlo** [comment]
There is a Debian `Dockerfile` in `tests/` that I've been using to test in.  You should be able to switch it to Alpine fairly easily.
