### ISSUE TITLE
How to create and use databases in locations other than the home directory?

### ISSUE THREAD

**Issue by hThoreau** [Evidlo/passhole#19]
```
> ph init --database .passwords/passhole.kdbx --gpgkey C621168D1F47B41583FDADCA18EABE4717B18556
usage: ph [-h] [--debug] [--cache PATH] [--no-cache] [--gpgkey FINGERPRINT]
          [--keyfile PATH] [--no-keyfile] [--no-password] [--database PATH]
          [-v]
          {show,type,add,remove,rm,edit,move,mv,list,ls,grep,init,dump} ...
ph: error: unrecognized arguments: --database .passwords/passhole.kdbx --gpgkey C621168D1F47B41583FDADCA18EABE4717B18556
> 
```
```
> command ph --path .passwords/passhole.kdbx --gpgkey C621168D1F47B41583FDADCA18EABE4717B18556 init    
usage: ph [-h] [--debug] [--cache PATH] [--no-cache] [--gpgkey FINGERPRINT]                            
          [--keyfile PATH] [--no-keyfile] [--no-password] [--database PATH]                            
          [-v]
          {show,type,add,remove,rm,edit,move,mv,list,ls,grep,init,dump} ...                            
ph: error: argument command: invalid choice: '.passwords/passhole.kdbx' (choose from 'show', 'type', 'add', 'remove', 'rm', 'edit', 'move', 'mv', 'list', 'ls', 'grep', 'init', 'dump') 
```
The above code was my attempt at it.

**Comment by Evidlo** [comment]
Move `init` to the end.  `--database` and `--gpgkey` are arguments to ph, not init.

**Comment by hThoreau** [comment]
Cool, that worked. Now, how could I set that to be the default database location? To do that I tried editing `~/.config/passhole,ini` like so:

```
[default]
database: /home/user/.passhole/passhole.kdbx
keyfile: /home/user/.passhole/passhole.key
```

But, even when using the `@` prefix, I'm not able to manipulate it.

```
> ph add @default/Gitlab
No database found at /home/user/.passhole.kdbx.  Run ph init
```

**Comment by Evidlo** [comment]
Add `default: True` to set a database as the default.  The name doesn't have to be `default`.

If you run delete your config/database/key, the init command should generate each and a config with all the correct options set.

**Comment by hThoreau** [comment]
Still not getting it.

```
> ph init
Enter your desired database password
Password: 
Confirm: 
Creating database at /home/user/.passhole.kdbx
Would you like to generate a keyfile? (Y/n): n
> cat .config/passhole.ini
[default]
database: /home/user/.passhole/passhole.kdbx
keyfile: /home/user/.passhole/passhole.key
default: True
> ls .passhole/
> 
```

**Comment by Evidlo** [comment]
Upgrade to the latest version:
``` bash
root@0faaf2075e9d:/home/passhole# mkdir ~/.passhole
root@0faaf2075e9d:/home/passhole# ph --version
1.8.2
root@0faaf2075e9d:/home/passhole# ph --database ~/.passhole/passhole.kdbx init
Please enter a name for the database (no spaces): passhole
Would you like the database to be password protected? (Y/n): n
Would you like to use a keyfile? (Y/n): n
Creating database at /root/.passhole/passhole.kdbx
Creating config at /root/.config/passhole.ini
root@0faaf2075e9d:/home/passhole# cat ~/.config/passhole.ini 
[passhole]
default = True
database = /root/.passhole/passhole.kdbx
no-password = True

root@0faaf2075e9d:/home/passhole# ph add test -w
Username: foo
URL: foo
```

**Comment by hThoreau** [comment]
That version isn't available through pip3.
 
```
> pip3 install passhole==1.8.2 --user
Collecting passhole==1.8.2                                                                              
  Could not find a version that satisfies the requirement passhole==1.8.2 (from versions: 0.1, 0.2, 0.2.
post1, 0.2.post2, 0.2.post3, 0.2.post4, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 1.0, 1.1, 1.1.post1, 1.1.post2, 1.2, 1.2.1, 1.2.2, 1.2.2.post1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.2, 1.5.2.post1, 1.5.4, 1.5.5, 1.6.0, 1.6.1, 1.7, 1.7.post1, 1.7.2, 1.7.3, 1.7.3.post1, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.8.0)
No matching distribution found for passhole==1.8.2
> pip3 install passhole==1.8.0 --user
Collecting passhole==1.8.0
  Using cached https://files.pythonhosted.org/packages/94/81/71ceb4cfe74e9eb4e146406e5e063b301801e84291d2d257ebde0cef3d85/passhole-1.8.0.tar.gz
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from passhole==1.8.0) (0.3.7)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from passhole==1.8.0) (0.16.0)
Requirement already satisfied: pygpgme in /home/user/.local/lib/python3.7/site-packages (from passhole==1.8.0) (0.3)
Requirement already satisfied: pykeepass in /home/user/.local/lib/python3.7/site-packages (from passhole==1.8.0) (3.0.3)
Requirement already satisfied: pynput in /home/user/.local/lib/python3.7/site-packages (from passhole==1.8.0) (1.4)
Requirement already satisfied: argon2-cffi in /home/user/.local/lib/python3.7/site-packages (from pykeepass->passhole==1.8.0) (19.1.0)
Requirement already satisfied: construct in /home/user/.local/lib/python3.7/site-packages (from pykeepass->passhole==1.8.0) (2.9.45)
Requirement already satisfied: pycryptodome in /home/user/.local/lib/python3.7/site-packages (from pykeepass->passhole==1.8.0) (3.7.3)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from pykeepass->passhole==1.8.0) (2.7.3)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from pykeepass->passhole==1.8.0)
(4.3.1)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /usr/lib/python3/dist-packages (from pynput->passhole==1.8.0) (0.23)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynput->passhole==1.8.0) (1.12.0)
Requirement already satisfied: cffi>=1.0.0 in /home/user/.local/lib/python3.7/site-packages (from argon2-cffi->pykeepass->passhole==1.8.0) (1.12.2)
Requirement already satisfied: pycparser in /home/user/.local/lib/python3.7/site-packages (from cffi>=1.0.0->argon2-cffi->pykeepass->passhole==1.8.0) (2.19)                                                   
Building wheels for collected packages: passhole
  Running setup.py bdist_wheel for passhole ... done
  Stored in directory: /home/user/.cache/pip/wheels/77/7e/21/db83d4611d05ba6825172c7ea15ebb081b58326bced36bc6b7
Successfully built passhole
Installing collected packages: passhole
  Found existing installation: passhole 1.7.7
    Uninstalling passhole-1.7.7:
      Successfully uninstalled passhole-1.7.7
Successfully installed passhole-1.8.0
> ph init
Traceback (most recent call last):
  File "/home/user/.local/bin/ph", line 10, in <module>                                                
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/passhole/passhole.py", line 903, in main         
    args.func(args)
  File "/home/user/.local/lib/python3.7/site-packages/passhole/passhole.py", line 130, in init_database
    if not os.path.exists(args.database):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists                                         
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType                    
>      
```

**Comment by Evidlo** [comment]
Ok, I just published it.

**Comment by hThoreau** [comment]
Ok, it worked, thanks!
