### ISSUE TITLE
"Could not decrypt cache" when opening external database

### ISSUE THREAD

**Issue by Lurkki14** [Evidlo/passhole#21]
This error occurs when trying to open the external database without --nocache:
```
ph --database <database> show <entry>
Could not decrypt cache
```

**Comment by Evidlo** [comment]
Try deleting your cache and see if it works.

**Comment by Lurkki14** [comment]
Then this happens:
```
passhole --database <database> show <entry>
Enter password: 
Traceback (most recent call last):
  File "/usr/bin/passhole", line 11, in <module>
    load_entry_point('passhole==1.5.0', 'console_scripts', 'passhole')()
  File "/usr/lib/python3.7/site-packages/passhole/passhole.py", line 510, in main
    args.func(args)
  File "/usr/lib/python3.7/site-packages/passhole/passhole.py", line 239, in show
    kp = open_database(args)
  File "/usr/lib/python3.7/site-packages/passhole/passhole.py", line 188, in open_database
    create_password_cache(args.cache, password, args.gpgkey)
  File "/usr/lib/python3.7/site-packages/passhole/passhole.py", line 134, in create_password_cache
    gpg.encrypt([selected_key], 0, infile, outfile)
gpgme.GpgmeError: (7, 53, 'Unusable public key')
```

**Comment by Evidlo** [comment]
See "Troubleshooting gpg" in the readme.

**Comment by Evidlo** [comment]
Did this work out for you?

**Comment by Lurkki14** [comment]
It's throwing the same error, gpg2 -K shows one key with trust level ultimate

**Comment by Evidlo** [comment]
I removed all GPG password caching in favor of holding the database open in a background process, so this issue doesn't exist anymore.
