### ISSUE TITLE
Cannot rename group

### ISSUE THREAD

**Issue by vdng** [Evidlo/passhole#47]
version 1.9.5 installed with pip

Renaming an entry is totally fine, but an error is thrown when trying to renaming a group with `edit` or `mv`.

```
~/dotfiles > ph edit Voyages/                                                                                                                                                                 
Name: voyage
Traceback (most recent call last):
  File "/home/trungtin/.local/bin/ph", line 33, in <module>
    sys.exit(load_entry_point('passhole==1.9.5', 'console_scripts', 'ph')())
  File "/home/trungtin/.local/lib/python3.9/site-packages/passhole/passhole.py", line 1113, in main
    args.func(args)
  File "/home/trungtin/.local/lib/python3.9/site-packages/passhole/passhole.py", line 874, in edit
    group.name = value
  File "/home/trungtin/.local/lib/python3.9/site-packages/rpyc/core/netref.py", line 165, in __setattr__
    syncreq(self, consts.HANDLE_SETATTR, name, value)
  File "/home/trungtin/.local/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/trungtin/.local/lib/python3.9/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/trungtin/.local/lib/python3.9/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
AttributeError: cannot access 'name'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 615, in _handle_setattr
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 536, in _access_attr
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 508, in _check_attr
AttributeError: cannot access 'name'

WARNING: Remote is on RPyC 4.1.5 and local is on RPyC 5.0.1.
```

**Comment by Evidlo** [comment]
This should be fix if you do a `pip install pykeepass-cache --upgrade`

**Comment by vdng** [comment]
Still the same issue after `pip install pykeepass-cache --upgrade`

**Comment by Evidlo** [comment]
vdng.  Sorry about that.  There was an old release of the package uploaded to PyPi incorrectly as version 3.0.0, while the release I just made is version 2.0.2.  I've deleted it so it should download the newest release now.
