### ISSUE TITLE
AttributeError: 'list' object has no attribute 'strip'

### ISSUE THREAD

**Issue by lufv** [Evidlo/passhole#50]
Hello there! When adding and showing entries or groups in either database created in KeePassXC or passhole I get following error:
```
$ ph add 123/
Traceback (most recent call last):
  File "/usr/bin/ph", line 33, in <module>
    sys.exit(load_entry_point('passhole==1.9.7', 'console_scripts', 'ph')())
  File "/usr/lib/python3.9/site-packages/passhole/passhole.py", line 1138, in main
    args.func(args)
  File "/usr/lib/python3.9/site-packages/passhole/passhole.py", line 790, in add
    parent_group = get_group(kp, group_path)
  File "/usr/lib/python3.9/site-packages/passhole/passhole.py", line 103, in get_group
    group = kp.find_groups(path=path, first=True)
  File "/usr/lib/python3.9/site-packages/rpyc/core/netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/lib/python3.9/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
AttributeError: 'list' object has no attribute 'strip'

========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 347, in find_groups
    res = self._find(prefix, group_xp, path=path, tree=group, **kwargs)
  File "/usr/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 289, in _find
    path = path.strip('/')
  File "/usr/lib/python3.9/site-packages/rpyc/core/netref.py", line 153, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/lib/python3.9/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: 'list' object has no attribute 'strip'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 608, in _handle_getattr
    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 536, in _access_attr
    return accessor(obj, name, *args)
AttributeError: 'list' object has no attribute 'strip'
```
I have installed passhole from pip on Alpine Linux. Thanks for any help!

**Comment by ernstki** [comment]
I'm seeing this, too, on macOS with Python 3.7.8 from MacPorts and passhole 1.9.7 from PyPI. Trying now to get you some more details on that.
